"""Chat history model

Revision ID: 19dfdbf5b193
Revises: 4579ccae4313
Create Date: 2024-05-01 16:37:20.779490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "19dfdbf5b193"
down_revision = "4579ccae4313"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("w2_form_id", sa.Integer(), nullable=False),
        sa.Column("user_query", sa.Text(), nullable=False),
        sa.Column("ai_response", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["w2_form_id"],
            ["w2_form.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chat_history")
    # ### end Alembic commands ###
