"""w2form data model

Revision ID: 4579ccae4313
Revises: 6c965aa59177
Create Date: 2024-04-30 13:26:56.386213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4579ccae4313"
down_revision = "6c965aa59177"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "w2_form",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("w2_form")
    # ### end Alembic commands ###
